spring.application.name=clinic-master-service

server.port=8080
server.servlet.context-path=/api

#config eureka and config server
eureka.client.serviceUrl.defaultZone=http://localhost:8085/eureka/
spring.config.import=configserver:http://localhost:8085/config

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=master-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.clinicanimal.master.web.dto.personal.PersonalRequestDto